name: "Deploy Site Contents"
on: push

jobs:
  sync_to_site:
    name: Deploy site files
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys
        run: |
          # Set SSH key
          mkdir -p ~/.ssh/
          echo '${{ secrets.DEPLOY_KEY }}' > ~/.ssh/deploy_key.pem
          /usr/bin/chmod 0600 ~/.ssh/deploy_key.pem

          # Set SSH_AUTH_SOCK
          /usr/bin/ssh-agent -a /tmp/ssh-auth.sock
          SSH_AUTH_SOCK=/tmp/ssh-auth.sock; export SSH_AUTH_SOCK;
          /usr/bin/ssh-add ~/.ssh/deploy_key.pem
      - uses: actions/checkout@v3
      - name: rsync current files
        run: |
          DEPLOY_FOLDER="${{ github.ref_name }}"
          DEPLOY_FOLDER=${DEPLOY_FOLDER//[^[:alnum:]]/-}
          rsync -av -i ~/.ssh/deploy_key.pem ./ ubuntu@dict-training.intelimina.com:/var/www/site/$DEPLOY_FOLDER/
